import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5001';

const products = [
  { id: 1, name: 'Aurelia Lounge Chair', category: 'Furniture', price: 349, rating: 4.9, reviews: 124, badge: 'Bestseller', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=700&q=85' },
  { id: 2, name: 'Solace Table Lamp', category: 'Lighting', price: 129, rating: 4.8, reviews: 89, badge: 'New arrival', image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=85' },
  { id: 3, name: 'Celine Ceramic Set', category: 'Decor', price: 89, rating: 4.7, reviews: 56, badge: '', image: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=700&q=85' },
  { id: 4, name: 'Noma Side Table', category: 'Furniture', price: 219, rating: 4.9, reviews: 102, badge: 'Limited', image: 'https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=700&q=85' }
];

function App() {
  const [cart, setCart] = useState([]);
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const [notice, setNotice] = useState('');
  const [cartOpen, setCartOpen] = useState(false);
  const [authOpen, setAuthOpen] = useState(false);
  const [authMode, setAuthMode] = useState('login');
  const [account, setAccount] = useState(() => JSON.parse(localStorage.getItem('nexa-account') || 'null'));
  const [authForm, setAuthForm] = useState({ name: '', email: '', password: '' });
  const [authError, setAuthError] = useState('');
  const [authLoading, setAuthLoading] = useState(false);
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [orderForm, setOrderForm] = useState({ fullName: '', address: '', city: '' });
  const [orderError, setOrderError] = useState('');
  const [orderLoading, setOrderLoading] = useState(false);
  const [adminOpen, setAdminOpen] = useState(false);
  const [adminStats, setAdminStats] = useState(null);
  const [adminError, setAdminError] = useState('');
  const readApiResponse = async response => { const raw = await response.text(); try { return JSON.parse(raw); } catch { throw new Error('The API response was not valid. Restart the NexaCart backend from this project folder and try again.'); } };
  const cartCount = cart.reduce((sum, item) => sum + item.qty, 0);
  const cartTotal = cart.reduce((sum, item) => sum + item.qty * item.price, 0);
  const filtered = useMemo(() => products.filter(p => (category === 'All' || p.category === category) && p.name.toLowerCase().includes(query.toLowerCase())), [query, category]);
  const addToCart = product => {
    setCart(items => items.some(i => i.id === product.id) ? items.map(i => i.id === product.id ? { ...i, qty: i.qty + 1 } : i) : [...items, { ...product, qty: 1 }]);
    setNotice(`${product.name} added to your bag`); setTimeout(() => setNotice(''), 2200);
  };
  const changeQuantity = (id, amount) => setCart(items => items.flatMap(item => item.id === id ? (item.qty + amount > 0 ? [{ ...item, qty: item.qty + amount }] : []) : [item]));
  const openAuth = mode => { setAuthMode(mode); setAuthError(''); setAuthOpen(true); };
  const submitAuth = async event => { event.preventDefault(); setAuthError(''); setAuthLoading(true); try { const response = await fetch(`${API_URL}/api/auth/${authMode === 'login' ? 'login' : 'register'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(authForm) }); const data = await readApiResponse(response); if (!response.ok) throw new Error(data.message || 'Unable to continue.'); localStorage.setItem('nexa-token', data.token); localStorage.setItem('nexa-account', JSON.stringify(data.user)); setAccount(data.user); setAuthOpen(false); setNotice(`Welcome${data.user.name ? `, ${data.user.name}` : ''}. Your account is ready.`); } catch (error) { setAuthError(error.message.includes('fetch') ? 'Start the API in a second terminal, then try again.' : error.message); } finally { setAuthLoading(false); } };
  const submitOrder = async event => { event.preventDefault(); setOrderError(''); setOrderLoading(true); try { const response = await fetch(`${API_URL}/api/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${localStorage.getItem('nexa-token')}` }, body: JSON.stringify({ items: cart.map(({ name, price, qty }) => ({ name, price, quantity: qty })), shippingAddress: orderForm }) }); const data = await readApiResponse(response); if (!response.ok) throw new Error(data.message || 'Order could not be placed.'); setCart([]); setCheckoutOpen(false); setCartOpen(false); setNotice(`Order ${data._id ? `#${data._id.slice(-6).toUpperCase()}` : ''} confirmed. Thank you.`); } catch (error) { setOrderError(error.message.includes('fetch') ? 'Start the API and connect MongoDB before placing live orders.' : error.message); } finally { setOrderLoading(false); } };
  const openAdmin = async () => { setAdminOpen(true); setAdminError(''); setAdminStats(null); try { const response = await fetch(`${API_URL}/api/admin/overview`, { headers: { Authorization: `Bearer ${localStorage.getItem('nexa-token')}` } }); const data = await readApiResponse(response); if (!response.ok) throw new Error(data.message || 'Unable to load dashboard.'); setAdminStats(data); } catch (error) { setAdminError(error.message.includes('fetch') ? 'Start the API and connect MongoDB to view live analytics.' : error.message); } };
  return <>
    <header className="topbar"><span>Complimentary delivery on orders over $150</span><span>Pakistan · USD</span></header>
    <nav className="nav"><a className="brand" href="#top">NEXA<span>CART</span></a><div className="links"><a href="#shop">Shop</a><a href="#collections">Collections</a><a href="#journal">Journal</a></div><div className="nav-actions"><label className="search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search pieces" /></label>{account?.role === 'admin' && <button className="admin-link" onClick={openAdmin}>Dashboard</button>}{account ? <button className="account-name" onClick={() => { localStorage.removeItem('nexa-token'); localStorage.removeItem('nexa-account'); setAccount(null); setNotice('You have been signed out.'); }}>Hi, {account.name?.split(' ')[0]} ↗</button> : <button onClick={() => openAuth('login')} aria-label="Account">♙</button>}<button className="bag" onClick={() => setCartOpen(true)} aria-label="Shopping bag">Bag <b>{cartCount}</b></button></div></nav>
    {notice && <div className="toast">✓ {notice}</div>}
    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="eyebrow">THE AUTUMN EDIT</p><h1>Objects with<br/><em>intention.</em></h1><p className="intro">Considered pieces for spaces that feel unmistakably yours. Made to be lived with, made to last.</p><a href="#shop" className="button">Explore collection <span>→</span></a></div><div className="hero-image"><img src="https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1400&q=90" alt="Refined living room"/><div className="floating-card"><small>CURATED FOR YOU</small><strong>Quiet forms. Lasting impact.</strong><a href="#shop">Discover now →</a></div></div></section>
      <section className="benefits"><div><b>✦</b><span><strong>Thoughtfully sourced</strong><small>Design with a story</small></span></div><div><b>◌</b><span><strong>Made to endure</strong><small>Quality without compromise</small></span></div><div><b>↗</b><span><strong>Delivered with care</strong><small>Free over $150</small></span></div></section>
      <section id="shop" className="shop"><div className="section-head"><div><p className="eyebrow">NEW THIS SEASON</p><h2>Made for your everyday</h2></div><a href="#shop">View all pieces →</a></div><div className="filters"><button className={category === 'All' ? 'active' : ''} onClick={() => setCategory('All')}>All pieces</button>{['Furniture','Lighting','Decor'].map(c => <button className={category === c ? 'active' : ''} onClick={() => setCategory(c)} key={c}>{c}</button>)}</div><div className="products">{filtered.map(p => <article className="product" key={p.id}><div className="image-wrap">{p.badge && <span className="badge">{p.badge}</span>}<button className="heart" aria-label="Add to wishlist">♡</button><img src={p.image} alt={p.name}/><button className="quick-add" onClick={() => addToCart(p)}>Add to bag <span>+</span></button></div><div className="product-info"><div><h3>{p.name}</h3><p>{p.category}</p></div><strong>${p.price}</strong></div><p className="rating">★ {p.rating} <span>({p.reviews})</span></p></article>)}</div></section>
      <section className="reloved"><div className="section-head"><div><p className="eyebrow">NEXA RELOVED</p><h2>Give remarkable pieces another life.</h2></div><span className="circular-label">↻ CIRCULAR MARKETPLACE</span></div><p className="reloved-intro">A considered resale edit—quality pieces, transparently graded and ready for their next chapter.</p><div className="reloved-grid">{[{name:'Studio Denim Jacket',brand:'Khaadi',condition:'Like new',price:58,image:'/re-loved/denim-jacket.png'},{name:'Silk Evening Kurti',brand:'Sapphire',condition:'Excellent',price:72,image:'/re-loved/silk-kurti.png'},{name:'Pastel Gold Gharara',brand:'Maria B',condition:'Like new',price:115,image:'/re-loved/pastel-gold-gharara.png'}].map(item => <article className="reloved-card" key={item.name}><div><img src={item.image} alt={item.name}/><span>RELOVED</span></div><p>{item.brand} · <b>{item.condition}</b></p><h3>{item.name}</h3><strong>${item.price}</strong></article>)}</div><div className="marketplace-note"><span>01</span><p><b>Made to circulate.</b> Sell, discover, or bid on pieces that deserve more than one story.</p><a href="#shop">Explore the marketplace →</a></div></section>
      <section id="collections" className="story"><img src="https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1000&q=85" alt="Minimal home interior"/><div><p className="eyebrow">OUR POINT OF VIEW</p><h2>Good design changes how a room feels.</h2><p>We believe the objects you choose should bring ease, warmth and a sense of self to every day.</p><a href="#journal" className="text-link">Read our story →</a></div></section>
    </main><footer id="journal"><a className="brand" href="#top">NEXA<span>CART</span></a><p>Design-led living, delivered.</p><small>© 2026 NexaCart. Crafted with intention.</small></footer>
    <div className={`drawer-backdrop ${cartOpen ? 'show' : ''}`} onClick={() => setCartOpen(false)}></div>
    <aside className={`cart-drawer ${cartOpen ? 'open' : ''}`}><div className="drawer-head"><div><p className="eyebrow">YOUR SELECTION</p><h2>Your bag <sup>{cartCount}</sup></h2></div><button onClick={() => setCartOpen(false)}>×</button></div>{cart.length ? <><div className="cart-items">{cart.map(item => <div className="cart-item" key={item.id}><img src={item.image} alt=""/><div><h3>{item.name}</h3><p>${item.price}</p><div className="quantity"><button onClick={() => changeQuantity(item.id,-1)}>−</button><span>{item.qty}</span><button onClick={() => changeQuantity(item.id,1)}>+</button></div></div><strong>${item.price * item.qty}</strong></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><strong>${cartTotal}</strong></div><small>Shipping and taxes calculated at checkout.</small><button className="checkout" onClick={() => account ? setCheckoutOpen(true) : openAuth('login')}>{account ? 'Continue to checkout →' : 'Sign in to checkout →'}</button></div></> : <div className="empty-bag"><p>Your bag is waiting for something beautiful.</p><button onClick={() => setCartOpen(false)}>Explore pieces →</button></div>}</aside>
    {authOpen && <div className="auth-layer"><div className="auth-card"><button className="auth-close" onClick={() => setAuthOpen(false)}>×</button><p className="eyebrow">NEXACART ACCOUNT</p><h2>{authMode === 'login' ? 'Welcome back.' : 'Create your account.'}</h2><p className="auth-copy">{authMode === 'login' ? 'Sign in to view your orders and saved pieces.' : 'Join a more considered way to shop.'}</p><form onSubmit={submitAuth}>{authMode === 'register' && <label>Full name<input required value={authForm.name} onChange={e => setAuthForm({ ...authForm, name: e.target.value })} placeholder="Your name" /></label>}<label>Email address<input required type="email" value={authForm.email} onChange={e => setAuthForm({ ...authForm, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<input required type="password" minLength="6" value={authForm.password} onChange={e => setAuthForm({ ...authForm, password: e.target.value })} placeholder="At least 6 characters" /></label>{authError && <p className="auth-error">{authError}</p>}<button className="auth-submit" disabled={authLoading}>{authLoading ? 'Please wait…' : authMode === 'login' ? 'Sign in →' : 'Create account →'}</button></form><p className="auth-switch">{authMode === 'login' ? 'New to NexaCart?' : 'Already have an account?'} <button onClick={() => { setAuthMode(authMode === 'login' ? 'register' : 'login'); setAuthError(''); }}>{authMode === 'login' ? 'Create one' : 'Sign in'}</button></p></div></div>}
    {checkoutOpen && <div className="auth-layer"><div className="auth-card checkout-card"><button className="auth-close" onClick={() => setCheckoutOpen(false)}>×</button><p className="eyebrow">SECURE CHECKOUT</p><h2>Delivery details.</h2><div className="checkout-total"><span>Order total</span><strong>${cartTotal}</strong></div><form onSubmit={submitOrder}><label>Recipient name<input required value={orderForm.fullName} onChange={e => setOrderForm({ ...orderForm, fullName: e.target.value })} placeholder="Full name" /></label><label>Delivery address<input required value={orderForm.address} onChange={e => setOrderForm({ ...orderForm, address: e.target.value })} placeholder="House, street, area" /></label><label>City<input required value={orderForm.city} onChange={e => setOrderForm({ ...orderForm, city: e.target.value })} placeholder="Karachi" /></label>{orderError && <p className="auth-error">{orderError}</p>}<button className="auth-submit" disabled={orderLoading}>{orderLoading ? 'Confirming order…' : `Place order · $${cartTotal}`}</button></form><p className="checkout-reassurance">◇ Encrypted checkout · Order confirmation by email</p></div></div>}
    {adminOpen && <div className="auth-layer"><div className="admin-panel"><button className="auth-close" onClick={() => setAdminOpen(false)}>×</button><p className="eyebrow">NEXACART ADMIN</p><h2>Store overview.</h2><p className="admin-subtitle">A real-time snapshot of your marketplace.</p>{adminError ? <p className="auth-error">{adminError}</p> : !adminStats ? <p className="admin-loading">Loading analytics…</p> : <><div className="metric-grid"><div><span>Revenue</span><strong>${adminStats.revenue.toLocaleString()}</strong></div><div><span>Orders</span><strong>{adminStats.orders}</strong></div><div><span>Customers</span><strong>{adminStats.users}</strong></div><div><span>Products</span><strong>{adminStats.products}</strong></div></div><div className="admin-next"><b>Next action</b><p>Add product-management and order-status controls here as your store catalogue grows.</p></div></>}</div></div>}
  </>;
}
createRoot(document.getElementById('root')).render(<App />);

if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js'));
